#include "Automat.h"
#include <iostream>
using namespace std;

void print(TType a){
	switch(a){
	case 0: cout<<"0";break;
	case 1: cout<<"integer"<<endl;break;
	case 2: cout<<"identifier"<<endl;break;
	case 3: cout<<"lexem"<<endl;break;
	case 4: cout<<"if"<<endl;break;
	case 5: cout<<"while"<<endl;break;
	case 6: cout<<"kommentar"<<endl;break;
	case 7: cout<<"plusToken"<<endl;break;
	case 8: cout<<"minus"<<endl;break;
	case 9: cout<<"slash"<<endl;break;
	case 10: cout<<"stern"<<endl;break;
	case 11: cout<<"kleiner"<<endl;break;
	case 12: cout<<"groesser"<<endl;break;
	case 13: cout<<"gleich"<<endl;break;
	case 14: cout<<"gleichGleich"<<endl;break;
	case 15: cout<<"ungleich"<<endl;break;
	case 16: cout<<"ausrufezeichen"<<endl;break;
	case 17: cout<<"und"<<endl;break;
	case 18: cout<<"semikolon"<<endl;break;
	case 19: cout<<"rundeklammerauf"<<endl;break;
	case 20: cout<<"rundeklammerzu"<<endl;break;
	case 21: cout<<"geschweifteklammerauf"<<endl;break;
	case 22: cout<<"geschweifteklammerzu"<<endl;break;
	case 23: cout<<"eckigeklammerauf"<<endl;break;
	case 24: cout<<"eckigeklammerzu"<<endl;break;
	case 25: cout<<"error"<<endl;break;
	default:  cout<<"other"<<endl;break;
	}
}

int main (int argc, char* argv[]){

	Automat* automat;

	automat = new Automat();


TType a = automat->checkChar('!');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('<');
print(a);
a = automat->checkChar(':');
print(a);
a = automat->checkChar('>');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(':');
print(a);
a = automat->checkChar('=');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('3');
print(a);
a = automat->checkChar('3');
print(a);
a = automat->checkChar('(');
print(a);
a = automat->checkChar('(');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('p');
print(a);
a = automat->checkChar('e');
print(a);
a = automat->checkChar('n');
print(a);
a = automat->checkChar('i');
print(a);
a = automat->checkChar('s');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('i');
print(a);
a = automat->checkChar('f');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('w');
print(a);
a = automat->checkChar('h');
print(a);
a = automat->checkChar('i');
print(a);
a = automat->checkChar('l');
print(a);
a = automat->checkChar('e');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('/');
print(a);
a = automat->checkChar('*');
print(a);
a = automat->checkChar('h');
print(a);
a = automat->checkChar('i');
print(a);
a = automat->checkChar('*');
print(a);
a = automat->checkChar('/');
print(a);
a = automat->checkChar('=');
print(a);
a = automat->checkChar('=');
print(a);
a = automat->checkChar(']');
print(a);
a = automat->checkChar(']');
print(a);
a = automat->checkChar('<');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('*');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(':');
print(a);
a = automat->checkChar('!');
print(a);
a = automat->checkChar('!');
print(a);

a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('<');
print(a);
a = automat->checkChar('<');
print(a);
a = automat->checkChar('<');
print(a);
a = automat->checkChar(':');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('/');
print(a);
a = automat->checkChar('/');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar('<');
print(a);
a = automat->checkChar(':');
print(a);
a = automat->checkChar('>');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(' ');
print(a);
a = automat->checkChar(';');
print(a);
a = automat->checkChar('(');
print(a);
a = automat->checkChar('(');
print(a);
a = automat->checkChar('=');
print(a);
a = automat->checkChar('=');
print(a);
a = automat->checkChar('{');
print(a);
a = automat->checkChar('{');
print(a);
a = automat->checkChar(':');
print(a);
a = automat->checkChar(':');
print(a);
a = automat->checkChar('%');
print(a);
a = automat->checkChar('%');
print(a);
a = automat->checkChar('!');
print(a);
a = automat->checkChar('!');
print(a);
a = automat->checkChar(' ');
print(a);

}
